name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-typescript:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Lint TypeScript
      run: yarn lint
    
    - name: Build TypeScript
      run: yarn build
    
    - name: Run TypeScript tests
      run: yarn test

  test-rust:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: rust
    
    - name: Check Rust formatting
      run: cd rust && cargo fmt --check
    
    - name: Lint Rust code
      run: cd rust && cargo clippy -- -D warnings
    
    - name: Run Rust tests
      run: cd rust && cargo test
    
    - name: Test TypeScript type generation
      run: cd rust && cargo run --bin generate-types --features ts-rs

  build-ios:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-apple-ios,aarch64-apple-ios-sim,x86_64-apple-ios
    
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: rust
    
    - name: Build iOS libraries
      run: |
        cd rust
        bash install-prerequisites.sh
        EAS_BUILD_PLATFORM=ios bash build.sh

  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-linux-android,x86_64-linux-android
    
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c
    
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: rust
    
    - name: Install cargo-ndk
      run: cargo install cargo-ndk
    
    - name: Build Android libraries
      run: |
        cd rust
        export ANDROID_HOME=$ANDROID_SDK_ROOT
        EAS_BUILD_PLATFORM=android bash build.sh

  check-types:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: rust
    
    - name: Check TypeScript types are up to date
      run: yarn check-types
